export const actions = {
  FETCHED_PRODUCTS: "FETCHED_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CHANGE_QTY: "CHANGE_QTY",
  OPT_CATEGORY: "OPT_CATEGORY",
  OPT_BRAND: "OPT_BRAND",
  OPT_CATEGORY_VALUE: "OPT_CATEGORY_VALUE",
  OPT_BRAND_VALUE: "OPT_BRAND_VALUE",
  PRODUCT_ACC_TO_CATEGORY: "PRODUCT_ACC_TO_CATEGORY",
  PRODUCT_ACC_TO_BRAND: "PRODUCT_ACC_TO_BRAND",
  INPUT_VALUE: "INPUT_VALUE",
};
